CC = gcc
CFLAGS = -g -Wall # flags when *compiling*
LFLAGS = -g -Wall # flags when *linking*
LIBS = -lm # math library
SOURCES = entropy.c invdist.c uf.c calc_fitness.c sort_population.c improvement.c operators.c hobma.c
OBJECTS = $(SOURCES:.c=.o)
EXECUTABLE = hobma

all: $(EXECUTABLE)

$(EXECUTABLE) : $(OBJECTS)
	$(CC) $(LFLAGS) $(OBJECTS) -o $@ $(LIBS)

%.o:%.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(OBJECTS) $(EXECUTABLE)
	
	
